version: '2'
services:
  frps-docker:
    build: ../.
    image: frp:latest
    container_name: frps-docker
    hostname: frps-docker
    environment:
      - FRP_TOKEN=${TOKEN}
      - FRP_MODE=frps
    ports:
      - "${BIND_PORT}:7000/tcp"
      - "${BIND_PORT}:7000/udp"
      - "${BIND_UDP_PORT}:7001/udp"
      - "${DASHBOARD_PORT}:7500/tcp"
      - "${VHOST_HTTP_PORT}:80/tcp"
      - "${VHOST_HTTPS_PORT}:443/tcp"