version: '2'
services:
  frpc-docker:
    build: ../.
    image: frp:latest
    container_name: frpc-docker
    hostname: frpc-docker
    volumes:
      - "./frpc.ini:/etc/frp/frpc.ini"
    environment:
      - SERVER_IP=136.244.110.67
      - PASSWORD=chobon
      - FRP_MODE=frpc