version: '2'
services:
  frpc-docker:
    build: ../.
    image: frp:latest
    container_name: frpc-docker
    hostname: frpc-docker
    volumes:
      - "./frpc.ini:/usr/local/frp/conf"
    environment:
      - str_log_level=info
    restart: always
    command: frpc