version: '2'
services:
  frpc-docker:
    build: ../.
    image: frp:latest
    container_name: frpc-docker
    hostname: frpc-docker
    volumes:
      - "./frpc.ini:/etc/frp/frpc.ini"
    environment:
      - FRP_SERVER_ADDR=${SERVER_ADDR}
      - FRP_SERVER_PORT=${SERVER_PORT}
      - FRP_TOKEN=${TOKEN}
      - FRP_MODE=frpc